# Dependencies
markdown:         kramdown

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Core
title:            Aftab Khalid
description:      Personal static website.
email:            xeeafui@gmail.com

source:           scaffold
destination:      _ak_pages

# host:             0.0.0.0
# port:             9001
baseurl:          /designs
url:              https://aftabkhalid.github.io
encoding:         UTF-8

# Custom vars
current_version:  0.1.5
repo:             git@github.com:aftabkhalid/designs.git


plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
